name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to unzip the code archive
      - name: Unzip code
        run: unzip code.zip -d extracted_code
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          
      # Step to run code scanning
      - name: Run Code Scanning
        uses: github/codeql-action@v2
        with:
          # Path to the extracted code directory
          sarif-file: extracted_code/codeql-results.sarif

      # Step to run dependabot
      - name: Run Dependabot
        uses: github/dependabot-action@v2
        with:
          # Path to the extracted code directory
          directory: extracted_code

      # Step to run secret scanning
      - name: Run Secret Scanning
        uses: github/secret-scanning-action@v1
        with:
          # Path to the extracted code directory
          path: extracted_code
