name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
        # required for all workflows
        security-events: write
  
        # required to fetch internal or private CodeQL packs
        packages: read
  
        # only required for workflows in private repositories
        actions: read
        contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: csharp
          build-mode: autobuild
        - language: javascript-typescript
          build-mode: none
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to unzip the code archive
      - name: Unzip code
        run: unzip demo-csharp-main.zip -d extracted_code
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis ${{ matrix.language }}
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
      
      # Step to run code scanning
      #- name: Run Code Scanning
      #  uses: github/codeql-action@v2
      #  with:
      #    # Path to the extracted code directory
      #    sarif-file: extracted_code/codeql-results.sarif

      # Step to run dependabot
      #- name: Run Dependabot
      #  uses: github/dependabot-action@v2
      #  with:
      #    # Path to the extracted code directory
      #    directory: extracted_code

      # Step to run secret scanning
      #- name: Run Secret Scanning
      #  uses: github/secret-scanning-action@v1
      #  with:
      #    # Path to the extracted code directory
      #    path: extracted_code
